# Generated by Django 4.2.6 on 2023-11-22 14:05

from django.db import migrations, models
import document_management_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.FileField(default='', upload_to=document_management_app.models.document_path),
        ),
    ]
